TARGET_GCC = -O3
TARGET_NVCC = -O3

# CUDA_ROOT_PATH = /home/fluffymelon/cuda-12.3/
CUDA_ROOT_PATH = /opt/modules/nvidia/cuda/12.9/
# CUDA_ROOT_PATH = /opt/modules/nvhpc/26.3/Linux_x86_64/26.3/cuda/13.1

BOOST_INCLUDE = /usr/local/boost/include/

AMGCL_INCLUDE = ../../../../../AmgCL/amgcl/

CUDA_ARCH = sm_80

FLOAT_TYPE = double

USE_APPLE_OMP = False

CUDA_AWARE_MPI = False

ENABLE_PROFILING = True

BUILD_DIR = bin
