test_polynom_indexing.bin: test_polynom_indexing.cpp
	g++ -I../../../.. -std=c++11 test_polynom_indexing.cpp -o test_polynom_indexing.bin
test_subterms_enum.bin: test_subterms_enum.cpp
	g++ -I../../../.. -std=c++11 test_subterms_enum.cpp -o test_subterms_enum.bin
monom_enum_util_ord2.bin: monom_enum_util.cpp
	g++ -I../../../.. -std=c++11 monom_enum_util.cpp -o monom_enum_util_ord2.bin